language: node_js
node_js:
- 8.4.0
install:
- npm update -g
- npm install
script:
- npm run build
env:
  global:
    - secure: "KbJDRDTEJx1WEugMNvyMWM9U8Xnn9fOADC86AviEHqR9L2Bl1viRmXMYWLihqRbdQylNqm9F7y/51r/glvOYGJ0foeemT3i5/Gg4tyhU+9pgupISwwGtwfef8Try5++3xYfGStrUofzDbB32SGuyLzV1zlTj2tqYgQqFaX+X3TtCT7FeiBc0R2VSOlJ6RZimVVlMPJqDY6k9YjIrRhZg36obTy7RwEEm9iyisBtTOgyzaqZWFRKZVOUxxGCIEDOl6MKM4Sgw3wRqKw+vzfMbRiExHTUqlrPlJUxKjC9G7JgfUTdqCK2tto7/X0vBpHZ/A2COIH4jZ5fSmDuAlF7HP1+PysLNGEy4zUE/S2hir4YzG47lKNLDNQjtYa4fPo6g7QVjGAwHjX2xmtlv2TmZWwVEm+kVH7jYiqdTm8KI2m2gyzxV5Jk/8lFNYpjNtSLx6lf/81i1Mul8ggMRbZMTBFsolHGBAaEOYUarKueV1A81SswFKjZJrxlOZUAibT4wV6V5Rl5icRTk8rt/v53wfXF/H+QWfbD1r/870OtGnkiIoFl86NPPtXaZ2KqxNX+3iujViviGt8ygxFw1cz4xcbm1NSbhLD4/JWWDuMFuMDr2ombrzkQAraK00P7+iXdEmlc/86YkEjOCJ+2EtcBr7Q1abNAP2GLotjtBEJiN+xA="
    - secure: "T5H70kSilmE3Q5/shPWRv2rcH4sXXUg8oDX6X981UBaFiIMSLWsWnQ0L0Gsy+Xkqe0cUo7DTxXvuaIM+I2N0HZxCyFW9slpRb+mNRve6aXQWDKmg5f79nUhEmhDqVRvNCeEkN31VuuJpy3fXzuHDC1LU+2x1brPtZFnxssfz/JFpgL5xx5LMI7sqqPQBWCeRHn0azxBwdCAtH17e+e04S5K8P179X6zxn1a+9wyzU5WSwcY2PFFLlhbpT6H6Wtt+CMGY3+FFLDtjxYRWCvo918fJeWk9BX25f17uU0EWNM8zhSwSWaW1mfLz4k26S0MFZ1+z/tA89sCVDEmKZpN4Gh7mzFNKh73LuhrjDcHA9ZtDcwX344EAAgrVuREFBmDeQXqPV8H8WyonQLMlj19j4RRuR7i2e5KHwYblWQmRBHYY5BC7IGuDvXdy6b3uPVHHlBgsW5f6eU9sSHU4fu6VgicCxs5zI7Vr+qeDXAFaVNVprMlbcFHbxgMFX4nNnsG/wxj+aUD3FsLobs+PX2K0O2xPE+2PaXIDo/GeYsEB0kLQdwiK/q+SB9Jr/ZL4917oLLCiAAjQh/AYNpwV5v25jJ32xHXQP+u5nmX35QiWT13Rg5J2Kb6dRWJXhmt0xxi1/Aeg6ECdnN/L5lralg2FzIM+J0usLOJARqJfFHuh+l0="
after_success:
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" -a $TRAVIS_BRANCH = "build" ]; then bash ./travis/run_on_build; fi
