name: build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn install --pure-lockfile

      - name: Test
        run: yarn run test

      - name: Build
        run: yarn run build
        env:
          NODE_ENV: "prod"
      # - name: Deploy
      #   run: docker-compose run deploy
      #   env:
      #     DEPLOY_KEY: ${{ secrets.deploy_key }}
